// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfk4ZgLhGooYrf8rOhsPUEWrwlZfSC844',
    appId: '1:634753910530:web:176637f54539f56986641b',
    messagingSenderId: '634753910530',
    projectId: 'internship-assignment-8d058',
    authDomain: 'internship-assignment-8d058.firebaseapp.com',
    storageBucket: 'internship-assignment-8d058.appspot.com',
    measurementId: 'G-3WK079DK7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGTlI4HW8oO5larBofsShD4kkG4JRvOk',
    appId: '1:634753910530:android:1a3045e736f10ac986641b',
    messagingSenderId: '634753910530',
    projectId: 'internship-assignment-8d058',
    storageBucket: 'internship-assignment-8d058.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCefaF9kOaCbiqyOzBC2PG5aEt_yUBZsb0',
    appId: '1:634753910530:ios:fb5c1180e0b910e386641b',
    messagingSenderId: '634753910530',
    projectId: 'internship-assignment-8d058',
    storageBucket: 'internship-assignment-8d058.appspot.com',
    iosClientId:
        '634753910530-kocj3138c2rjvuu79ie1r8ng71mnllhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipAssignment',
  );
}
